version: '2'
services: 

  eventposter:
    build: ./eventposter
    volumes: 
        - ./eventposter:/go/src/github.com/jetbasrawi/app
    links:
      - eventstore
  eventstore:
    build: ./eventstore
    ports:  
      - "2113:2113"
      - "1113:1113"
